AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deployment of EC2 instance and security group as nested stack.'
Metadata:
  Author: FilipKamenar
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "EC2 instance information"
        Parameters:
          - InstanceName
          - InstanceType
          - InstanceImageId
          - KeyName
      -
        Label:
          default: "Networking information"
        Parameters:
          - Vpc
          - Subnet
          - IngressIpAddress
          - RdsSecurityGroup
      -
        Label:
          default: "CFN template URL location in S3 - Object URL value"
        Parameters:
          - CfnEc2SgTemplate


Parameters:
  InstanceName:
    Type: String
    Description: Name of EC2 instance.
  InstanceType:
    Type: String
    Description: Type of EC2 instance.
    Default: t3a.small
  InstanceImageId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Description: AMI ID of the EC2 instance as latest value from public SSM parameter store.
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable access to the instance.
  Vpc:
    Type: AWS::EC2::VPC::Id
    Description: Specify VPC ID.
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Specify subnet ID.
  IngressIpAddress:
    Type: String
    Description: Value of IPv4 address in CIDR format accessing EC2 instance from internet.
    Default: '0.0.0.0/0'
  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: RDS security group ID.
  CfnEc2SgTemplate:
    Type: String
    Description: URL location of CFN template in S3.

Resources:
  Ec2InstanceSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref CfnEc2SgTemplate
      TimeoutInMinutes: 10
      Parameters:
        InstanceName: !Ref InstanceName
        InstanceType: !Ref InstanceType
        InstanceImageId: !Ref InstanceImageId
        KeyName: !Ref KeyName
        SgName: !Sub ${InstanceName}-ec2-instance-sg
        Vpc: !Ref Vpc
        Subnet: !Ref Subnet
        RdsSecurityGroup: !Ref RdsSecurityGroup
        IngressIpAddress: !Ref IngressIpAddress